name: Prueba de Tokens

on:
  push:

jobs:
  comparar-tokens:
    runs-on: self-hosted
    steps:
      - name: Comparar DEV_TOKEN (Secret) con LOCAL_DEV_TOKEN (Local)
        env:
          GH_SECRET_DEV: ${{ secrets.DEV_TOKEN }}
        shell: powershell
        run: |
          Write-Output "Comparando tokens..."
          
          if ($env:GH_SECRET_DEV -eq $env:LOCAL_DEV_TOKEN) {
            Write-Output "Los tokens coinciden"
          } else {
            Write-Output "Los tokens no coinciden"
            exit 1
          }
